version: "3"
services:
  papermc:
    image: marcermarc/papermc:latest
    volumes:
      - ./data:/mnt/minecraft
    ports:
      - 25565:25565/tcp
      - 25565:25565/udp
    stdin_open: true
    tty: true